feat: [search] define search interface
linuxdeepin/dtkio pull request #17
Opened 2022-11-17 05:28 UTC by Kakueeen

define search interface

Log: define search interface
Task: https://pms.uniontech.com/task-view-202689.html

2022-11-17 06:23 UTC, Johnson-zs requested changes

2022-11-18 08:07 UTC, Johnson-zs requested changes

2022-11-18 08:07 UTC, Johnson-zs commented on dtksearch/include/dtksearchtypes.h
> +    PinYin = 0x02 | FileName,
这是什么操作，0x02呢？

2022-11-21 02:26 UTC, Kakueeen commented on dtksearch/include/dtksearchtypes.h
> +    PinYin = 0x02 | FileName,
参考的WindowType，指定拼音搜索的时候，同时也会召回匹配的文件名结果

2022-11-23 03:53 UTC, toberyan commented
+1

2022-11-23 03:55 UTC, xzl01 commented on dtksearch/include/dtksearchtypes.h
> +    PinYin = 0x02 | FileName,
枚举需要在代码中加入符合doxygen标准的英文注释

2022-11-23 05:10 UTC, Groveer reviewed
+1

2022-11-23 05:28 UTC, Johnson-zs commented on debian/libdtksearch-dev.install
> +/usr/share/*/doc/*.qch
这个似乎不用在最前面加 /，可以统一处理下

2022-11-23 05:53 UTC, Kakueeen commented on dtksearch/include/dtksearchtypes.h
> +    PinYin = 0x02 | FileName,
枚举注释，下次提交时处理

2022-11-23 08:25 UTC, xzl01 reviewed
/+1

2022-11-23 10:09 UTC, xzl01 approved these changes

2022-11-23 10:09 UTC, Kakueeen commented
/merge

2022-11-23 10:10 UTC, merged