feat: [mount] implement functions of protocol monitor.
linuxdeepin/dtkio pull request #2
Opened 2022-10-09 06:56 UTC by itsXuSt

as title.

Log: feature implement.

2022-10-09 09:31 UTC, toberyan reviewed
+1

2022-10-09 12:32 UTC, Groveer reviewed
+1

2022-10-09 12:32 UTC, xzl01 commented on dtkmount/include/dprotocoldevicemonitor.h
> +    // TODO(xust) should the property separated from Block devices?
建议使用TODO tag的风格，方便软件识别定位：https://www.jetbrains.com/help/clion/using-todo.html

2022-10-10 09:41 UTC, itsXuSt commented on dtkmount/include/dprotocoldevicemonitor.h
> +    // TODO(xust) should the property separated from Block devices?
> 建议使用TODO tag的风格，方便软件识别定位：https://www.jetbrains.com/help/clion/using-todo.html

QtCreator 可通过官方插件支持 TODO/FIXME 列表查看。
不过不支持多行 TODO；
![image](https://user-images.githubusercontent.com/50353838/194838412-e6b35b37-4163-4eb1-83d0-8b019ba6a7e9.png)

2022-10-14 02:51 UTC, itsXuSt commented
/check

2022-10-14 02:52 UTC, itsXuSt commented
/check build

2022-10-18 05:15 UTC, Johnson-zs requested changes

2022-10-18 05:15 UTC, Johnson-zs commented on dtkmount/include/dprotocoldevice.h
> +    kNever = 0,
枚举命名不用k前缀了

2022-10-18 05:15 UTC, Johnson-zs commented on dtkmount/src/dprotocoldevice_p.h
> +
同上

2022-10-18 05:15 UTC, Johnson-zs commented on dtkmount/src/dprotocoldevice_p.h
> +    int timeout = 3;
建议保持{}风格初始化

2022-10-18 05:15 UTC, Johnson-zs commented on dtkmount/src/utils.h
> +static constexpr char kRegxDaemonMountPath[] { "^/media/.*/smbmounts/" };
头文件用inline？

2022-10-18 05:18 UTC, Johnson-zs requested changes

2022-10-18 05:18 UTC, Johnson-zs commented on dtkmount/src/utils.cpp
> +/*!
注释使用 @~english

2022-10-18 05:35 UTC, Johnson-zs requested changes

2022-10-18 05:35 UTC, Johnson-zs commented on dtkmount/include/dprotocoldevicemonitor.h
> +    virtual ~DProtocolDeviceMonitor();
似乎可以直接在后面加override，不用virtual

2022-10-18 05:36 UTC, Johnson-zs requested changes

2022-10-18 05:36 UTC, Johnson-zs commented on dtkmount/include/dprotocoldevice.h
> +enum PasswdSave {
存在ABI稳定风险，建有优化，或者在此添加 TODO

2022-10-18 05:36 UTC, Johnson-zs commented on dtkmount/include/dblockdevicemonitor.h
> +    virtual ~DBlockDeviceMonitor();
同

2022-10-18 05:36 UTC, Johnson-zs commented on dtkmount/include/dprotocoldevice.h
> +    virtual ~DProtocolDevice();
同

2022-10-19 05:20 UTC, itsXuSt commented
@Johnson-zs 所有 comments 已整改。

2022-10-19 05:46 UTC, Johnson-zs approved these changes

2022-10-19 05:51 UTC, toberyan approved these changes
+1

2022-10-19 05:57 UTC, xzl01 approved these changes

2022-10-19 05:59 UTC, Groveer reviewed
+1

2022-10-19 06:03 UTC, dandan-y reviewed
+1

2022-10-19 06:05 UTC, merged