feat: [io] add async function in io
linuxdeepin/dtkio pull request #27
Opened 2022-12-13 01:52 UTC by misonlan

add async function in io

Log: add async function

Task: https://pms.uniontech.com/task-view-223189.html

2022-12-13 02:55 UTC, Groveer reviewed
+1

2022-12-13 03:04 UTC, Johnson-zs requested changes

2022-12-13 03:04 UTC, Johnson-zs commented on dtkio/include/dfileinfo.h
>      ~DFileInfo();
复制构造如何处理？

2022-12-13 03:04 UTC, Johnson-zs commented on dtkio/include/dfilemonitor.h
>  private:
同，出了文件信息都不需要改

2022-12-13 04:08 UTC, toberyan commented
+1

2022-12-14 03:28 UTC, misonlan commented on dtkio/include/dfileinfo.h
>      ~DFileInfo();
在dfileinfo里面使用的裸指针，增加了复制构造移动构造等接口

2022-12-14 03:28 UTC, misonlan commented on dtkio/include/dfile.h
>  private:
统一使用了命名空间前缀

2022-12-14 03:28 UTC, misonlan commented on dtkio/include/dfilemonitor.h
>  private:
已改

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/include/dfilefuture.h
> +    void infoAttribute(AttributeID id, const QVariant &value);
感觉信号重载的话，不是很好用吧

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/include/dfilemonitor.h
> +    DTK_CORE_NAMESPACE::DExpected<void> setWatchType(WatchType type);
void 干嘛 expected？

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/src/dfile.cpp
> +#include <QtConcurrent/QtConcurrentRun>
头文件顺序错了，应该是 c -> c++ -> 第三方库的顺序，其他自查

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/src/dfile.cpp
> +    QtConcurrent::run([&]() {
如果lambda，建议只捕获要用到的变量

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/src/dfile.cpp
> +        if (gerror)
引用捕获的它会不会有生命周期的问题

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/src/dfileinfo_p.h
> +class DFileInfoPrivate : public QObject, public QSharedData
这里有用到什么QOBject的特性吗，如果没用到可以delete，减少对象体积

2022-12-14 03:31 UTC, Johnson-zs commented on dtkio/src/dfileoperator.cpp
> +    QtConcurrent::run([&]() {
其他类似的lambda都自查下，同上，不要引用捕获全部，并且一定要注意引用补获的生命周期！

2022-12-14 03:47 UTC, misonlan commented on dtkio/src/dfile.cpp
> +#include <QtConcurrent/QtConcurrentRun>
已改

2022-12-14 03:48 UTC, misonlan commented on dtkio/include/dfilefuture.h
> +    void infoAttribute(AttributeID id, const QVariant &value);
统一接口，直接说明是同一数据的不同获取方式

2022-12-14 03:49 UTC, misonlan commented on dtkio/src/dfileinfo_p.h
> +class DFileInfoPrivate : public QObject, public QSharedData
使用了信号相关

2022-12-22 09:08 UTC, xzl01 commented on dtkio/include/DtkIOGlobal
> +// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
其实大写的头文件不需要加SPDX头 直接在dep5中指定就好

2023-01-10 07:22 UTC, toberyan approved these changes

2023-01-10 07:23 UTC, lanxuesong commented
/merge

2023-01-10 07:33 UTC, toberyan commented
/merge

2023-01-10 07:33 UTC, merged